---
- name: "Extract zip artifact"
  become: true
  shell: |
    echo $(pwd)
    # tar -xvf ./artifact.tar.gz
    register: print_result

- name: print message
  debug:
    msg: "{{ print_result.stdout_lines }}"

# - name: "Start the App"
#   become: true
#   shell: |
#     npm install
#     pm2 stop default
#     pm2 start npm -- start  